public class VariablesTheme {	
    public static void main(String[] args) {
    	System.out.println("\n1. Вывод значений переменных на консоль (это название задачи)"); 
    	byte numberOfCores = 4;
    	short voltagePC = 220;
    	int ramClockSpeed = 700000;
    	long processorСlockSpeed = 123456789001234L;
    	float lengthPC = 44.55F;
    	double widthPC = 21.456D;
		char seriesPC = 'A';
		boolean newPC = true;
		System.out.println("Количество ядер " + numberOfCores);
    	System.out.println("Напряжение ПК " + voltagePC);
    	System.out.println("Тактовая частота видеокарты " + ramClockSpeed);
    	System.out.println("Тактовая частота процессора " + processorСlockSpeed);
    	System.out.println("Длина ПК " + lengthPC);
    	System.out.println("Ширина ПК " + widthPC);
		System.out.println("Серия ПК " + seriesPC);
		System.out.println("Новый ПК " + newPC);
		 
		System.out.println("\n2. Расчет стоимости товара со скидкой"); 
		int penPrice = 100;
		int bookPrice = 200;
		int discount = 11;
		int totalCostNotDiscount;
		int amountDiscount;
		int totalCostWithDiscount;
		totalCostNotDiscount = penPrice + bookPrice;
		amountDiscount = (totalCostNotDiscount * 11) / 100;
		totalCostWithDiscount = totalCostNotDiscount - amountDiscount;
		System.out.println("Общая стоимость товаров без скидки " + totalCostNotDiscount);
		System.out.println("Сумма скидки " + amountDiscount);
		System.out.println("Общая стоимость товаров со скидкой " + totalCostWithDiscount);

		System.out.println("\n3. Вывод слова JAVA"); 
        System.out.println("   J    a  v     v  a"); 
        System.out.println("   J   a a  v   v  a a");
        System.out.println("J  J  aaaaa  V V  aaaaa");
        System.out.println(" JJ  a     a  V  a     a");

        System.out.println("\n4. Вывод min и max значений целых числовых типов");
        byte maxByte = 127;
    	short maxShort = 32767;
    	int maxInt = 2147483647;
    	long maxLong = 9223372036854775807L;
    	System.out.println(maxByte);
    	maxByte += 1;
		System.out.println(maxByte);
		maxByte -= 1;
		System.out.println(maxByte);
    	System.out.println(maxShort);
    	maxShort += 1;
		System.out.println(maxShort);
		maxShort -= 1;
		System.out.println(maxShort);
    	System.out.println(maxInt);
    	maxInt += 1;
    	System.out.println(maxInt);
		maxInt -= 1;
		System.out.println(maxInt);
		System.out.println(maxLong);
    	maxLong += 1;
		System.out.println(maxLong);
		maxLong -= 1;
		System.out.println(maxLong);

        System.out.println("\n5. Перестановка значений переменных");
        int a = 2;
        int b = 5;
        int c ;
        System.out.println("с помощью третьей переменной");
        System.out.println("a = " + a +" b = " + b);
        c = a;
        a = b;
        b = c;
        System.out.println("a = " + a +" b = " + b);
        System.out.println("с помощью арифметических операций");
        System.out.println("a = " + a +" b = " + b);
        a += b;
        b = a - b;
        a = a - b;
        System.out.println("a = " + a +" b = " + b);
        System.out.println("с помощью побитовой операции ^");
        System.out.println("a = " + a +" b = " + b);
        a = a ^ b;
        b = a ^ b;
        a = a ^ b;
        System.out.println("a = " + a +" b = " + b);

        System.out.println("\n6. Вывод символов и их кодов");
        char char35 = '#';
        char char38 = '&';
        char char64 = '@';
        char char94 = '^';
        char char95 = '_';
        int ascii; 
        ascii = (int) char35;
        System.out.println(char35 + " " + ascii);
        ascii = (int) char38;
        System.out.println(char38 + " " + ascii);
        ascii = (int) char64;
        System.out.println(char64 + " " + ascii);
        ascii = (int) char94;
        System.out.println(char94 + " " + ascii);
        ascii = (int) char95;
        System.out.println(char95 + " " + ascii);

        System.out.println("\n7. Вывод в консоль ASCII-арт Дюка");
        char z = '/';
        char x = '\\';
        char w = '_';
        char d = '(';
        char e = ')';
        System.out.println("  " + " " + " " + " " + z + x);
        System.out.println("  " + " " + " " + z + " " + " " + x);
        System.out.println("  " + " " + z + w + d + " " + e + x);
        System.out.println("  " + z + " " + " " + " " + " " + " " + " " + x);
        System.out.println(" " + z + w + w + w + w + z + x + w + w + x);
        
        System.out.println("\n8.Вывод количества сотен, десятков и единиц числа");
        int num = 123;
        int hundreds;
        int tens;
        int ones;
        int summa_digit;
        int product_digit;
        hundreds = num / 100;
        tens = num % 100 / 10;
        ones = num % 10;
        System.out.println("Число " + num + " содержит");
        System.out.println(hundreds + " сотен");
        System.out.println(tens + " десятков");
        System.out.println(ones + " единиц");
        summa_digit = hundreds + tens + ones;
        product_digit = hundreds * tens * ones;
        System.out.println("Сумма его цифр = " + summa_digit);
        System.out.println("Произведение = " + num + product_digit);

        System.out.println("\n9.Вывод времени");
        int seconds = 86399;
        int minutes;
        int hours;
        hours = seconds / 3600;
        minutes = seconds % 3600 / 60;
        seconds = seconds % 60;
        System.out.println(hours + ":" + minutes + ":" + seconds);
    }
}